# -*- mode: ruby -*-

Vagrant.configure(2) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    # Puppetmaster on CentOS 7
    puppet.vm.box = "centos/7"
    puppet.vm.hostname = "puppet.thinkedg.com"
    puppet.hostmanager.aliases = %w(puppet)
 end 

  config.vm.define "agent1" do |agent1|
    #Puppet agent on CentoOS 7
    agent1.vm.box = "centos/7"
    agent1.vm.hostname = "agent1.thinkedg.com"
    agent1.vm.network :private_network, ip: "10.0.20.11"
    agent1.hostmanager.aliases = %w(agent1)
  end

  config.vm.define "agent2" do |agent2|
    # puppet agent on Debian
    agent2.vm.box = "debian/jessie64"
    agent2.vm.hostname = "agent2.thinkedg.com"
    agent2.vm.network :private_network, ip: "10.0.20.12"
    agent2.hostmanager.aliases = %w(agent2)
  end
end
