# -*- mode: ruby -*-

Vagrant.configure(2) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
    puppet.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    # Puppetmaster on CentOS 7
    puppet.vm.box = "centos/7"
    puppet.vm.synced_folder ".", "/vagrant" , type: "virtualbox"
    puppet.vm.synced_folder "../code", "/puppet_code" , type: "virtualbox"
    puppet.vm.synced_folder "../puppetserver", "/puppet_puppetserver" , type: "virtualbox"
    puppet.vm.hostname = "puppet.thinkedg.com"
    puppet.vm.network :private_network, ip: "10.0.20.10"
    puppet.hostmanager.aliases = %w(puppet)
    puppet.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo yum install emacs -y
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum install puppetserver -y
      sudo rm -rf /etc/puppetlabs/code
      sudo ln -s /puppet_code /etc/puppetlabs/code
      sudo rm -rf /etc/puppetlabs/puppetserver
      sudo ln -s /puppet_puppetserver /etc/puppetlabs/puppetserver
      sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
      echo "*.thinkedg.com" | sudo tee /etc/puppetlabs/puppet/autosign.conf
      sudo systemctl start puppetserver
    SHELL
  end 

  config.vm.define "agent1" do |agent1|
    #Puppet agent on CentoOS 7
    agent1.vm.box = "centos/7"
    agent1.vm.hostname = "agent1.thinkedg.com"
    agent1.vm.network :private_network, ip: "10.0.20.11"
    agent1.hostmanager.aliases = %w(agent1)
    agent1.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum install puppet-agent -y
      sudo service puppet start
    SHELL
  end

  config.vm.define "agent2" do |agent2|
    # puppet agent on Debian
    agent2.vm.box = "debian/jessie64"
    agent2.vm.hostname = "agent2.thinkedg.com"
    agent2.vm.network :private_network, ip: "10.0.20.12"
    agent2.hostmanager.aliases = %w(agent2)
    agent2.vm.provision "shell", inline: <<-SHELL
      wget https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb
      sudo dpkg -i puppetlabs-release-pc1-jessie.deb
      sudo apt-get update
      sudo apt-get install puppet-agent -y
      sudo /opt/puppetlabs/bin/puppet agent --enable
      sudo service puppet start
    SHELL
  end
end
